name: Bump version
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo $PR
        env:
          PR: ${{ toJson(github.event.pull_request) }}
  build:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - run: git fetch origin +refs/heads/develop:refs/remotes/origin/develop
    - name: Setup git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1
      id: poetry-cache
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Increase project version
      run: |
        pip install --upgrade pip wheel
        pip install poetry
        poetry install
        make increase-version

    - name: Push changes to master
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.PAT_TOKEN }}
        tags: true
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "master"
        destination_branch: "develop"
        pr_title: "Master → Develop."
        pr_body: ":crown: *An automated PR*"
        pr_reviewer: "jackton1"
        pr_label: "auto-pr"
        github_token: ${{ secrets.GITHUB_TOKEN }}
