name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: git fetch origin +refs/heads/develop:refs/remotes/origin/develop
    - name: Setup git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1
      id: poetry-cache
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Increase project version
      run: |
        pip install --upgrade pip wheel
        pip install poetry
        poetry install
        make increase-version

    - name: Push changes to master
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
    - run: |
        git checkout develop
        git pull --allow-unrelated-histories
        git merge master --allow-unrelated-histories
    - name: Push changes to develop
      uses: ad-m/github-push-action@master
      with:
        branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
